### PR TITLE
Working Typescript build using gulp

### PR DESCRIPTION
**Pull request by barendb**
Hey Dude

I was scouring Github to try find an Angular2 & Typescript example and found your repo.

However I wanted to continue using gulp with my build process, so I tinkered around with your example and got it working, I noticed you had some commented out code in the gulpfile to compile the scripts :smiley_cat: 

TypeScript 1.5 Beta got pushed to NPM yesterday so that's what made it possible :smile:

### CODE REVIEW

**Comment by KhaosTheory1012** [comment]
src\CustomerController.ts(4,51): 2307 Cannot find external module 'angular2/angular2-bundle.js'.
src\CustomerController.ts(8,1): 1205 Decorators are only available when targeting ECMAScript 5 and higher.
src\ShoppingcartController.ts(4,51): 2307 Cannot find external module 'angular2/angular2'.
src\ShoppingcartController.ts(8,1): 1205 Decorators are only available when targeting ECMAScript 5 and higher.
src\main.ts(6,47): 2307 Cannot find external module 'angular2/angular2'.
src\main.ts(9,1): 1205 Decorators are only available when targeting ECMAScript 5 and higher.
src\show-properties.ts(4,51): 2307 Cannot find external module 'angular2/angular2'.
src\show-properties.ts(6,1): 1205 Decorators are only available when targeting ECMAScript 5 and higher.
src\testimport.ts(4,51): 2307 Cannot find external module 'angular2/angular2'.
src\testimport.ts(7,1): 1205 Decorators are only available when targeting ECMAScript 5 and higher.
src\todo.ts(4,51): 2307 Cannot find external module 'angular2/angular2'.
src\todo.ts(6,1): 1205 Decorators are only available when targeting ECMAScript 5 and higher.
src\tryout.ts(4,42): 2307 Cannot find external module 'angular2/angular2'.
src\tryout.ts(6,1): 1205 Decorators are only available when targeting ECMAScript 5 and higher.


Getting there right now. How did you resolve them? Tsc doesn't seem to find the angular2 module anymore.

**Comment by KhaosTheory1012** [comment]
If you find out how to use the regular angular2 release with the new typescript beta let me know. At the moment we try to figure out how to use the new router with typescript aswell as angular2 without that bundled version with this very minimalistic .d.ts . If you got a good resource for .d.ts files for angular2 let us know. 

Thanks! I opened a new branch for your Pull-Request.

**Comment by barendb** [comment]
No sorry, I'm trying to figure out the same thing ;)

On your previous comment, I get those warnings as well, but it still compiles and I was able to run one of your demo's fine.

**Comment by KhaosTheory1012** [comment]
Okay :D Thanks anyways I'll let you know if I find something out. 
At least it compiles.

**Pull request merged**
